// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class PlanetResources
{
        public const string achievement_rocket_engineer = "CgkI1KCwvoQTEAIQBA"; // <GPGSID>
        public const string leaderboard_taking_the_lead = "CgkI1KCwvoQTEAIQBw"; // <GPGSID>
        public const string achievement_intermediate = "CgkI1KCwvoQTEAIQAw"; // <GPGSID>
        public const string achievement_customer = "CgkI1KCwvoQTEAIQAQ"; // <GPGSID>
        public const string achievement_crush_em = "CgkI1KCwvoQTEAIQCA"; // <GPGSID>
        public const string achievement_beginner = "CgkI1KCwvoQTEAIQAg"; // <GPGSID>
        public const string achievement_meteor_buster = "CgkI1KCwvoQTEAIQBQ"; // <GPGSID>
        public const string achievement_toxic = "CgkI1KCwvoQTEAIQBg"; // <GPGSID>

}

